SELECT
	TABSCHEMA,
	TABNAME,
	'' || (COLNAME) || ' as ' || CASE
		TYPENAME WHEN 'BIGINT' THEN 'long'
		WHEN 'DATE' THEN 'date'
		WHEN 'DECIMAL' THEN 'decimal(' || LENGTH || ',' || SCALE || ')'
		WHEN 'DOUBLE' THEN 'float'
		WHEN 'INTEGER' THEN 'long'
		WHEN 'TIMESTAMP' THEN 'timestamp'
		WHEN 'VARGRAPHIC' THEN 'string'
	END || ',' AS dftype,
	COLNO,
	TYPENAME,
	LENGTH,
	SCALE
FROM
	SYSCAT.COLUMNS
WHERE
	TABNAME IN (
	'ASSETLOCUSERCUST',
	'BP_INVBALHISTORY',
	'COMMODITIES',
	'INVUSE',
	'LABOR',
	'MATRECTRANS',
	'MATUSETRANS',
	'SYNONYMDOMAIN')
ORDER BY
	TABSCHEMA,
	TABNAME,
	COLNO;
