SELECT
	TABSCHEMA,
	TABNAME,
	'StructField("' || COLNAME || '",' || CASE
		TYPENAME WHEN 'BIGINT' THEN 'LongType()'
		WHEN 'DATE' THEN 'DateType()'
		WHEN 'DECIMAL' THEN 'DecimalType(' || LENGTH || ',' || SCALE || ')'
		WHEN 'DOUBLE' THEN 'FloatType()'
		WHEN 'INTEGER' THEN 'LongType()'
		WHEN 'TIMESTAMP' THEN 'TimestampType()'
		WHEN 'VARGRAPHIC' THEN 'StringType()'
	END || ',True), \' AS Struct,
	COLNO,
	TYPENAME,
	LENGTH,
	SCALE
FROM
	SYSCAT.COLUMNS
WHERE
	TABNAME IN (
	'ASSETLOCUSERCUST',
'BP_INVBALHISTORY',
'COMMODITIES',
'INVUSE',
'LABOR',
'MATRECTRANS',
'MATUSETRANS',
'SYNONYMDOMAIN')
ORDER BY
	TABSCHEMA,
	TABNAME,
	COLNO;
